name: Contexts # Start Exercise build-applications-w-GHCP-agent-mode
run-name: Run by @${{ github.actor }}
on: [push, pull_request]
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
    steps:
      - run: echo "${{ github.actor }}" 
      - run: echo "${{ github.run_id }}" 
      - run: echo "${{ github.repository_owner }}"
      - run: echo "${{ github.event.pull_request.title }}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}