name: Manual # Start Manual build
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        description: 'Greeting to use'
        required: false
        default: 'Hello, World!'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"

# If you want to run this workflow in local cli,
# use the following command:
# gh workflow run manual.yml -f greeting=goodbye